import type { Player } from "../types/dataTypes"

const dummyPlayers: Player[] = [
  {
    "_id": "1",
    "playerPhoto": "",
    "playerName": "A. Bello",
    "playerFullName": "Abdulrahman Bello",
    "DOB": "14/03/2009",
    "nationality": "Nigeria",
    "height": 178,
    "preferredFoot": "",
    "ageGroup": "U-21",
    "status": "Free",
    "position": "RW",
    "goals": 0,
    "assists": 0,
    "rating": 7.9,
    "currentClubName": "",
    "currentClubLogo": "",
    "playerHistory": "",
    "playerAppearance": 0,
    "isFeatured": false,
    "isDraft": false
  },
  {
    "_id": "2",
    "playerPhoto": "https://res.cloudinary.com/dyeh9qvbl/image/upload/v1782596106/Gemini_Generated_Image_knt51xknt51xknt5-removebg-preview_vcykbl.png",
    "playerName": "L. Messi",
    "playerFullName": "Lionel Messi",
    "DOB": "24/06/1987",
    "nationality": "Argentina",
    "height": 170,
    "preferredFoot": "Left",
    "ageGroup": "U-21",
    "status": "Transferred",
    "position": "FW",
    "goals": 50,
    "assists": 49,
    "rating": 8.6,
    "currentClubName": "Inter Miami",
    "currentClubLogo": 'https://images.seeklogo.com/logo-png/50/1/ea-sports-fc-logo-png_seeklogo-503896.png',
    "playerHistory": "Lionel Messi is widely regarded as one of the greatest football players in history, renowned for his exceptional dribbling, playmaking, and goal-scoring abilities. He currently captains both Major League Soccer side Inter Miami CF and the Argentina national football",
    "playerAppearance": 60,
    "isFeatured": true,
    "isDraft": false
  },
  {
    "_id": "3",
    "playerPhoto": "",
    "playerName": "D. Yusuf",
    "playerFullName": "Daniel Yusuf",
    "DOB": "21/11/2004",
    "nationality": "Nigeria",
    "height": 186,
    "preferredFoot": "Right",
    "ageGroup": "U-23",
    "status": "Negotiation",
    "position": "CB",
    "goals": 2,
    "assists": 1,
    "rating": 7.7,
    "currentClubName": "Kaduna Warriors",
    "currentClubLogo": "",
    "playerHistory": "Daniel progressed through Kaduna's grassroots football system and spent three seasons with Kaduna Warriors, gaining experience as a composed ball playing defender.",
    "playerAppearance": 38,
    "isFeatured": true,
    "isDraft": true
  },
  {
    "_id": "4",
    "playerPhoto": "",
    "playerName": "E. James",
    "playerFullName": "Emmanuel James",
    "DOB": "18/09/2008",
    "nationality": "Nigeria",
    "height": 175,
    "preferredFoot": "Right",
    "ageGroup": "U-17",
    "status": "Free",
    "position": "CAM",
    "goals": 10,
    "assists": 12,
    "rating": 8.1,
    "currentClubName": "Jos Elite Academy",
    "currentClubLogo": "",
    "playerHistory": "Emmanuel joined Jos Elite Academy at the age of 11 after impressing scouts at a youth competition. He is known for his creativity and vision in m_idfield.",
    "playerAppearance": 12,
    "isFeatured": false,
    "isDraft": false
  },
  {
    "_id": "5",
    "playerPhoto": "",
    "playerName": "M. Ibrahim",
    "playerFullName": "Musa Ibrahim",
    "DOB": "10/01/2006",
    "nationality": "Nigeria",
    "height": 181,
    "preferredFoot": "Left",
    "ageGroup": "U-21",
    "status": "Transferred",
    "position": "LW",
    "goals": 14,
    "assists": 9,
    "rating": 8.3,
    "currentClubName": "Abuja Academy",
    "currentClubLogo": "",
    "playerHistory": "Musa developed his game in community football centers around Abuja before moving to Abuja Academy, where his pace and dribbling ability made him a standout winger.",
    "playerAppearance": 8,
    "isFeatured": false,
    "isDraft": false
  },
  {
    "_id": "6",
    "playerPhoto": "",
    "playerName": "K. Adeyemi",
    "playerFullName": "Kunle Adeyemi",
    "DOB": "23/08/2005",
    "nationality": "Nigeria",
    "height": 188,
    "preferredFoot": "Right",
    "ageGroup": "U-23",
    "status": "Negotiation",
    "position": "GK",
    "goals": 10,
    "assists": 10,
    "rating": 7.8,
    "currentClubName": "Ibadan FC",
    "currentClubLogo": "",
    "playerHistory": "Kunle started as an outfield player before transitioning to goalkeeper at age 14. His performances for Ibadan FC earned him attention from several domestic clubs.",
    "playerAppearance": 29,
    "isFeatured": true,
    "isDraft": true
  },
  {
    "_id": "7",
    "playerPhoto": "",
    "playerName": "P. Eze",
    "playerFullName": "Peter Eze",
    "DOB": "15/05/2009",
    "nationality": "Nigeria",
    "height": 172,
    "preferredFoot": "Left",
    "ageGroup": "U-17",
    "status": "Free",
    "position": "LB",
    "goals": 1,
    "assists": 6,
    "rating": 7.5,
    "currentClubName": "Owerri Academy",
    "currentClubLogo": "",
    "playerHistory": "Peter was recruited by Owerri Academy following an outstanding display at an interschool tournament. He has since become a reliable attacking fullback.",
    "playerAppearance": 11,
    "isFeatured": false,
    "isDraft": false
  },
  {
    "_id": "8",
    "playerPhoto": "",
    "playerName": "J. Ojo",
    "playerFullName": "Joseph Ojo",
    "DOB": "29/12/2007",
    "nationality": "Nigeria",
    "height": 184,
    "preferredFoot": "Right",
    "ageGroup": "U-21",
    "status": "Transferred",
    "position": "ST",
    "goals": 20,
    "assists": 4,
    "rating": 8.6,
    "currentClubName": "Ilorin Youths",
    "currentClubLogo": "",
    "playerHistory": "Joseph rose through the ranks at Ilorin Youths and established himself as a prolific striker, regularly attracting scouts from clubs across the country.",
    "playerAppearance": 29,
    "isFeatured": false,
    "isDraft": true
  },
  {
    "_id": "9",
    "playerPhoto": "",
    "playerName": "T. Hassan",
    "playerFullName": "Tijani Hassan",
    "DOB": "06/02/2004",
    "nationality": "Nigeria",
    "height": 180,
    "preferredFoot": "Right",
    "ageGroup": "U-23",
    "status": "Negotiation",
    "position": "CM",
    "goals": 5,
    "assists": 10,
    "rating": 8.0,
    "currentClubName": "Sokoto FC",
    "currentClubLogo": "",
    "playerHistory": "Tijani spent his formative years at Sokoto FC, where his technical ability and work rate helped him become a key figure in the m_idfield.",
    "playerAppearance": 30,
    "isFeatured": false,
    "isDraft": true
  },
  {
    "_id": "10",
    "playerPhoto": "",
    "playerName": "C. Umeh",
    "playerFullName": "Chinedu Umeh",
    "DOB": "09/10/2008",
    "nationality": "Nigeria",
    "height": 179,
    "preferredFoot": "Left",
    "ageGroup": "U-17",
    "status": "Free",
    "position": "RW",
    "goals": 9,
    "assists": 7,
    "rating": 7.8,
    "currentClubName": "Anambra Academy",
    "currentClubLogo": "",
    "playerHistory": "Chinedu joined Anambra Academy as a teenager and rap_idly gained recognition for his left foot, close control, and ability to create chances from w_ide areas.",
    "playerAppearance": 14,
    "isFeatured": false,
    "isDraft": true
  },

  {
    "_id": "11",
    "playerPhoto": "",
    "playerName": "I. Lawal",
    "playerFullName": "Ismail Lawal",
    "DOB": "11/06/2006",
    "nationality": "Nigeria",
    "height": 182,
    "preferredFoot": "Right",
    "ageGroup": "U-21",
    "status": "Transferred",
    "position": "RB",
    "goals": 3,
    "assists": 9,
    "rating": 7.9,
    "currentClubName": "Abeokuta FC",
    "currentClubLogo": "",
    "playerHistory": "Abeokuta FC",
    "playerAppearance": 32,
    "isFeatured": false,
    "isDraft": true
  },
  {
    "_id": "12",
    "playerPhoto": "",
    "playerName": "F. Dav_id",
    "playerFullName": "Felix Dav_id",
    "DOB": "04/04/2005",
    "nationality": "Nigeria",
    "height": 187,
    "preferredFoot": "Left",
    "ageGroup": "U-23",
    "status": "Negotiation",
    "position": "CB",
    "goals": 4,
    "assists": 1,
    "rating": 7.6,
    "currentClubName": "Makurdi Stars",
    "currentClubLogo": "",
    "playerHistory": "Benue Academy, Makurdi Stars",
    "playerAppearance": 37,
    "isFeatured": false,
    "isDraft": true
  },

  {
    "_id": "13",
    "playerPhoto": "",
    "playerName": "R. Simon",
    "playerFullName": "Raphael Simon",
    "DOB": "19/07/2009",
    "nationality": "Nigeria",
    "height": 174,
    "preferredFoot": "Right",
    "ageGroup": "U-17",
    "status": "Free",
    "position": "CAM",
    "goals": 8,
    "assists": 11,
    "rating": 8.0,
    "currentClubName": "Calabar Academy",
    "currentClubLogo": "",
    "playerHistory": "Calabar Academy",
    "playerAppearance": 26,
    "isFeatured": false,
    "isDraft": true
  },

  {
    "_id": "14",
    "playerPhoto": "",
    "playerName": "A. Yakubu",
    "playerFullName": "Aliyu Yakubu",
    "DOB": "08/09/2007",
    "nationality": "Nigeria",
    "height": 185,
    "preferredFoot": "Left",
    "ageGroup": "U-21",
    "status": "Transferred",
    "position": "LW",
    "goals": 16,
    "assists": 10,
    "rating": 8.5,
    "currentClubName": "Bauchi United Academy",
    "currentClubLogo": "",
    "playerHistory": "Bauchi United Academy",
    "playerAppearance": 5,
    "isFeatured": false,
    "isDraft": false
  },

  {
    "_id": "15",
    "playerPhoto": "",
    "playerName": "O. Peter",
    "playerFullName": "Oluwaseun Peter",
    "DOB": "16/12/2004",
    "nationality": "Nigeria",
    "height": 190,
    "preferredFoot": "Right",
    "ageGroup": "U-23",
    "status": "Negotiation",
    "position": "ST",
    "goals": 22,
    "assists": 3,
    "rating": 8.7,
    "currentClubName": "Lagos Islanders",
    "currentClubLogo": "",
    "playerHistory": "Lagos Islanders",
    "playerAppearance": 10,
    "isFeatured": false,
    "isDraft": false
  },

  {
    "_id": "16",
    "playerPhoto": "",
    "playerName": "E. Adebayo",
    "playerFullName": "Emmanuel Adebayo",
    "DOB": "12/02/2009",
    "nationality": "Nigeria",
    "height": 176,
    "preferredFoot": "Right",
    "ageGroup": "U-17",
    "status": "Free",
    "position": "RM",
    "goals": 7,
    "assists": 9,
    "rating": 7.8,
    "currentClubName": "Ekiti Future Stars",
    "currentClubLogo": "",
    "playerHistory": "Ekiti Future Stars",
    "playerAppearance": 39,
    "isFeatured": false,
    "isDraft": false
  },
  {
    "_id": '17',
    "playerPhoto": "",
    "playerName": "S. Musa",
    "playerFullName": "Suleiman Musa",
    "DOB": "28/05/2007",
    "nationality": "Nigeria",
    "height": 184,
    "preferredFoot": "Left",
    "ageGroup": "U-21",
    "status": "Transferred",
    "position": "CDM",
    "goals": 4,
    "assists": 8,
    "rating": 8.0,
    "currentClubName": "Katsina Elite Academy",
    "currentClubLogo": "",
    "playerHistory": "Katsina Elite Academy",
    "playerAppearance": 24,
    "isFeatured": false,
    "isDraft": true
  },
  {
    "_id": "18",
    "playerPhoto": "",
    "playerName": "J. Nwosu",
    "playerFullName": "Joshua Nwosu",
    "DOB": "09/11/2005",
    "nationality": "Nigeria",
    "height": 189,
    "preferredFoot": "Right",
    "ageGroup": "U-23",
    "status": "Negotiation",
    "position": "CB",
    "goals": 3,
    "assists": 1,
    "rating": 7.9,
    "currentClubName": "Aba Warriors Academy",
    "currentClubLogo": "",
    "playerHistory": "Aba Warriors Academy",
    "playerAppearance": 29,
    "isFeatured": false,
    "isDraft": true
  },
  {
    "_id": "19",
    "playerPhoto": "",
    "playerName": "C. Michael",
    "playerFullName": "Christian Michael",
    "DOB": "03/08/2008",
    "nationality": "Nigeria",
    "height": 173,
    "preferredFoot": "Left",
    "ageGroup": "U-17",
    "status": "Free",
    "position": "LW",
    "goals": 12,
    "assists": 10,
    "rating": 8.2,
    "currentClubName": "Benin Rising Stars",
    "currentClubLogo": "",
    "playerHistory": "Benin Rising Stars",
    "playerAppearance": 20,
    "isFeatured": false,
    "isDraft": true
  },
  {
    "_id": "20",
    "playerPhoto": "",
    "playerName": "T. Ibrahim",
    "playerFullName": "Tahir Ibrahim",
    "DOB": "21/04/2006",
    "nationality": "Nigeria",
    "height": 181,
    "preferredFoot": "Right",
    "ageGroup": "U-21",
    "status": "Transferred",
    "position": "CAM",
    "goals": 13,
    "assists": 11,
    "rating": 8.4,
    "currentClubName": "Minna Football Academy",
    "currentClubLogo": "",
    "playerHistory": "Minna Football Academy",
    "playerAppearance": 6,
    "isFeatured": false,
    "isDraft": true
  },
  {
    "_id": "21",
    "playerPhoto": "",
    "playerName": "D. Ekanem",
    "playerFullName": "Daniel Ekanem",
    "DOB": "17/01/2004",
    "nationality": "Nigeria",
    "height": 191,
    "preferredFoot": "Right",
    "ageGroup": "U-23",
    "status": "Negotiation",
    "position": "GK",
    "goals": 0,
    "assists": 1,
    "rating": 8.1,
    "currentClubName": "Uyo Academy",
    "currentClubLogo": "",
    "playerHistory": "Uyo Academy, Akwa Youths",
    "playerAppearance": 9,
    "isFeatured": false,
    "isDraft": true
  },
  {
    "_id": "22",
    "playerPhoto": "",
    "playerName": "A. Chukwu",
    "playerFullName": "Anthony Chukwu",
    "DOB": "14/10/2009",
    "nationality": "Nigeria",
    "height": 177,
    "preferredFoot": "Right",
    "ageGroup": "U-17",
    "status": "Free",
    "position": "RB",
    "goals": 2,
    "assists": 7,
    "rating": 7.6,
    "currentClubName": "Nsukka Youth Academy",
    "currentClubLogo": "",
    "playerHistory": "Nsukka Youth Academy",
    "playerAppearance": 12,
    "isFeatured": false,
    "isDraft": true
  },
  {
    "_id": "23",
    "playerPhoto": "",
    "playerName": "M. Sani",
    "playerFullName": "Muhammed Sani",
    "DOB": "26/06/2007",
    "nationality": "Nigeria",
    "height": 186,
    "preferredFoot": "Left",
    "ageGroup": "U-21",
    "status": "Transferred",
    "position": "ST",
    "goals": 19,
    "assists": 5,
    "rating": 8.6,
    "currentClubName": "Zaria United Academy",
    "currentClubLogo": "",
    "playerHistory": "Zaria United Academy",
    "playerAppearance": 17,
    "isFeatured": false,
    "isDraft": true
  },
  {
    "_id": "24",
    "playerPhoto": "",
    "playerName": "K. George",
    "playerFullName": "Kingsley George",
    "DOB": "30/03/2005",
    "nationality": "Nigeria",
    "height": 182,
    "preferredFoot": "Right",
    "ageGroup": "U-23",
    "status": "Negotiation",
    "position": "CM",
    "goals": 6,
    "assists": 9,
    "rating": 8.0,
    "currentClubName": "Yenagoa Stars",
    "currentClubLogo": "",
    "playerHistory": "Yenagoa Stars",
    "playerAppearance": 39,
    "isFeatured": false,
    "isDraft": true
  },
  {
    "_id": "25",
    "playerPhoto": "",
    "playerName": "P. Udo",
    "playerFullName": "Patrick Udo",
    "DOB": "07/12/2008",
    "nationality": "Nigeria",
    "height": 175,
    "preferredFoot": "Left",
    "ageGroup": "U-17",
    "status": "Free",
    "position": "CAM",
    "goals": 9,
    "assists": 13,
    "rating": 8.3,
    "currentClubName": "Eket Football School",
    "currentClubLogo": "",
    "playerHistory": "Eket Football School",
    "playerAppearance": 23,
    "isFeatured": true,
    "isDraft": false
  },
  {
    "_id": "26",
    "playerPhoto": "",
    "playerName": "L. Balogun",
    "playerFullName": "Lanre Balogun",
    "DOB": "19/09/2006",
    "nationality": "Nigeria",
    "height": 183,
    "preferredFoot": "Right",
    "ageGroup": "U-21",
    "status": "Transferred",
    "position": "RW",
    "goals": 15,
    "assists": 12,
    "rating": 8.5,
    "currentClubName": "Ijebu Stars Academy",
    "currentClubLogo": "",
    "playerHistory": "Ijebu Stars Academy",
    "playerAppearance": 14,
    "isFeatured": true,
    "isDraft": true
  },
  {
    "_id": "27",
    "playerPhoto": "",
    "playerName": "O. Matthew",
    "playerFullName": "Oche Matthew",
    "DOB": "22/02/2004",
    "nationality": "Nigeria",
    "height": 188,
    "preferredFoot": "Right",
    "ageGroup": "U-23",
    "status": "Negotiation",
    "position": "CDM",
    "goals": 4,
    "assists": 6,
    "rating": 7.9,
    "currentClubName": "Lokoja City FC",
    "currentClubLogo": "",
    "playerHistory": "Lokoja City FC Kogi Youths",
    "playerAppearance": 33,
    "isFeatured": false,
    "isDraft": false
  },
  {
    "_id": "28",
    "playerPhoto": "",
    "playerName": "B. Joseph",
    "playerFullName": "Bright Joseph",
    "DOB": "05/05/2009",
    "nationality": "Nigeria",
    "height": 171,
    "preferredFoot": "Left",
    "ageGroup": "U-17",
    "status": "Free",
    "position": "CF",
    "goals": 14,
    "assists": 4,
    "rating": 8.1,
    "currentClubName": "Ondo Youth Academy",
    "currentClubLogo": "",
    "playerHistory": "Ondo Youth Academy",
    "playerAppearance": 39,
    "isFeatured": false,
    "isDraft": true
  },
  {
    "_id": "29",
    "playerPhoto": "",
    "playerName": "I. Sunday",
    "playerFullName": "Isaac Sunday",
    "DOB": "13/07/2007",
    "nationality": "Nigeria",
    "height": 185,
    "preferredFoot": "Right",
    "ageGroup": "U-21",
    "status": "Transferred",
    "position": "LB",
    "goals": 2,
    "assists": 8,
    "rating": 7.8,
    "currentClubName": "Asaba Academy",
    "currentClubLogo": "",
    "playerHistory": "Asaba Academy",
    "playerAppearance": 18,
    "isFeatured": true,
    "isDraft": false
  },
  {
    "_id": "30",
    "playerPhoto": "https://res.cloudinary.com/dyeh9qvbl/image/upload/v1782596104/Gemini_Generated_Image_7d9awa7d9awa7d9a-removebg-preview_pnpjqh.png",
    "playerName": "N. Emmanuel",
    "playerFullName": "Nathaniel Emmanuel",
    "DOB": "24/11/2005",
    "nationality": "Nigeria",
    "height": 187,
    "preferredFoot": "Left",
    "ageGroup": "U-23",
    "status": "Negotiation",
    "position": "ST",
    "goals": 21,
    "assists": 6,
    "rating": 8.7,
    "currentClubName": "Warri Wolves Academy",
    "currentClubLogo": "",
    "playerHistory": "Warri Wolves Academy Delta Youth FC",
    "playerAppearance": 36,
    "isFeatured": false,
    "isDraft": false
  }
]

// export const fetchAllPlayers = async (): Promise<Player[]> => {
//   return new Promise((resolve) => {
//     setTimeout(() => {
//       resolve(dummyPlayers)
//     }, 1000)
//   })
// }

export const fetchAllPlayers = async (): Promise<Player[]> => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const shouldFail = false;

      if (shouldFail) {
        reject(new Error("Failed to fetch dummyPlayers"));
        return;
      }

      resolve(dummyPlayers);
    }, 1000);
  });
};

export const fetchSinglePlayer = async (_id: string): Promise<Player | null> => {
  return new Promise((resolve,) => {
    setTimeout(() => {
      const player = dummyPlayers.find((player) => player._id === _id)
      resolve(player ?? null)
    }, 1000)
  })
}

// export const fetchSinglePlayer = async (_id: string): Promise<Player | null> => {
//   return new Promise((resolve, reject) => {
//     setTimeout(() => {
//       const shouldFail = false;

//       if (shouldFail) {
//         reject(new Error("Failed to fetch dummyPlayers"));
//         return;
//       }
//       const player = dummyPlayers.find((player) => player._id === _id)
//       resolve(player ?? null)
//     }, 1000);
//   });
// };